# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160511_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 5, 12, 8, 4, 14, 826650, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
