# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160512_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='headline',
            new_name='head_line',
        ),
    ]
